platform :ios, '8.0'
pod 'SVProgressHUD'
pod 'YYCategories'
pod 'IQKeyboardManager'
pod 'SDWebImage'
pod 'MJRefresh'
pod 'RealReachability'
pod 'SDCycleScrollView'
pod 'Qiniu', :git => 'https://github.com/qiniu/objc-sdk.git', :branch => 'AFNetworking-3.x'
